steps:
  - name: Delete workflow runs
    uses: MajorScruffy/delete-old-workflow-runs@v0.2.0
    with:
      repository: binduwavell/zmk-config
      older-than-seconds: 86400  # remove all workflow runs older than 1 day
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}